name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  EXTNAME: SemanticReports
  MW_INSTALL_PATH: ${{ github.workspace }}

jobs:
  # style:
  #   name: Code Style
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: wikiteq/php-lint-action@main

  # security:
  #   name: Static Analysis
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - mediawiki: REL1_39
  #           smw: 4.2.0
  #         - mediawiki: REL1_43
  #           smw: 6.0.1
  #   steps:
  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
  #       with:
  #         php-version: '8.1'
  #         extensions: mbstring, intl, ast
  #         coverage: none
  #         tools: composer
  #     - name: Setup MediaWiki
  #       uses: actions/checkout@v4
  #       with:
  #         repository: wikimedia/mediawiki
  #         ref: ${{ matrix.mediawiki }}
  #     - name: Setup dependency - SemanticMediaWiki
  #       uses: actions/checkout@v4
  #       with:
  #         path: extensions/SemanticMediaWiki
  #         ref: ${{ matrix.smw }}
  #         repository: SemanticMediaWiki/SemanticMediaWiki
  #     - name: Setup Extension
  #       uses: actions/checkout@v4
  #       with:
  #         path: extensions/${{ env.EXTNAME }}
  #     - name: Setup Composer
  #       run: |
  #         echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
  #         composer update
  #         composer update
  #         composer config repositories.wikiteq/phan-mediawikiservices-check-plugin git https://github.com/WikiTeq/phan-mediawikiservices-check-plugin.git
  #         composer require "wikiteq/phan-mediawikiservices-check-plugin:v0.2.0"
  #     - name: Phan
  #       run: ./vendor/bin/phan -d extensions/${{ env.EXTNAME }} --minimum-target-php-version=8.1 --long-progress-bar

  # i18n-check:
  #   name: I18n check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: I18n check action
  #       uses: wikiteq/mediawiki-i18n-check-action@main
  #       with:
  #         extension: SemanticReports

  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      MW_INSTALL_PATH: ${{ github.workspace }}/mediawiki
    strategy:
      fail-fast: false
      matrix:
        include:
          - mediawiki: REL1_39
            smw: 4.2.0
            php: 8.1
          # - mediawiki: REL1_43
          #   smw: 6.0.1
          #   php: 8.3
    steps:
      - name: Setup Extension
        uses: actions/checkout@v4

      - name: Setup dependency - SemanticMediaWiki
        uses: actions/checkout@v4
        with:
          repository: SemanticMediaWiki/SemanticMediaWiki
          path: ${{ github.workspace }}/SemanticMediaWiki
          ref: ${{ matrix.smw }}

      # SMW 5.0.2 is pinned to using codesniffer 46.0.0, core REL1_43 uses
      # codesniffer 45.0.0, and our phpunit action loads all dev dependencies
      # of extensions; just delete all of SMW's
      - name: SMW - remove composer.json dev dependencies
        working-directory: ${{ github.workspace }}/SemanticMediaWiki
        run: jq 'delpaths([["require-dev"]])' composer.json > composer.json.tmp && mv composer.json.tmp composer.json

      # Make sure that ExtensionJsonValidationTest passes
      - name: SMW - remove invalid qunit tests
        working-directory: ${{ github.workspace }}/SemanticMediaWiki
        run: jq 'delpaths([["QUnitTestModule"]])' extension.json > extension.json.tmp && mv extension.json.tmp extension.json

      # Make sure that AutoLoaderStructureTest passes
      - name: SMW - add missing autoload entries
        if: ${{ matrix.smw == '6.0.1' }}
        working-directory: ${{ github.workspace }}/SemanticMediaWiki
        run: |
          jq '.AutoloadClasses."SMW\\Elastic\\ElasticStore" = "src/Elastic/ElasticStore.php" | .AutoloadClasses."SMW\\MediaWiki\\Search\\ExtendedSearchEngine" = "src/MediaWiki/Search/ExtendedSearchEngine.php"' \
            extension.json > extension.json.tmp && mv extension.json.tmp extension.json

      - name: SMW - fix maintenance autoload namespace entries
        if: ${{ matrix.smw == '6.0.1' }}
        working-directory: ${{ github.workspace }}/SemanticMediaWiki
        run: |
          jq '.AutoloadNamespaces."SMW\\Maintenance\\" = "maintenance/" | delpaths([["AutoloadNamespaces", "SMW\\Maintenance"]])' \
            extension.json > extension.json.tmp && mv extension.json.tmp extension.json

      # Make sure we don't get errors about return types
      # Cherry-pick https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5806
      - name: SMW - fix iterator return types
        if: ${{ matrix.smw === '4.2.0' }}
        working-directory: ${{ github.workspace }}/SemanticMediaWiki
        run: curl -L https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/84d564c16fe0dd4a62910c5ff1b596e75a647768.patch | git apply -v

      - name: Mediawiki PHPUnit
        uses: wikiteq/mediawiki-phpunit-action@master
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mediawiki }}
          extension: ${{ env.EXTNAME }}
          extra_file: .github/PHPUnitSettings.php
          use_mysql: true
